### ISSUE TITLE
Unable to convert target to Selenium By: link

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-xebium-bridge#2]
Hi @fhoeben ,

With Xebium I had this:

```
!define TEST_SYSTEM {slim} 
!path ./dependencies/*

|import|
|com.xebia.incubator.xebium|

| script | selenium driver fixture |
| start browser | firefox | on url | http://www.google.com.br/ |
| do | open | on | /imghp?hl=pt-BR&gws_rd=ssl |
| ensure | do | click | on | id=qbi |
| ensure | do | click | on | link=Envie uma imagem |
| ensure | do | sendKeys | on | id=qbfile | with | ${user.dir}/bradesco.jpg |
| ensure | do | click | on | name=btnG |
```

This performs a search my image, on the Brazilian google site. It works. Then I tried your bridge, like this:

```
!define TEST_SYSTEM {slim} 
!path ./dependencies/*

!define slim.timeout {40}

|Import                            |
|nl.hsac.fitnesse.fixture.slim     |
|nl.hsac.fitnesse.fixture.slim.web |
|nl.hsac.fitnesse.fixture.slim.web.xebium |

| script | selenium driver setup |
| start driver for | firefox |

| storyboard | hsac selenium driver fixture |
| start browser | firefox | on url | http://www.google.com.br/imghp?hl=pt-BR&gws_rd=ssl |
| ensure | do | click | on | id=qbi |
| ensure | do | click | on | link=Envie uma imagem |
| ensure | do | sendKeys | on | id=qbfile | with | ${user.dir}/bradesco.jpg |
| ensure | do | click | on | name=btnG |
```

Unfortunately it fails like this:  Unable to convert target to Selenium By: link=Envie uma imagem

Is the link-based strategy not supported by your bridge? Thanks!

**Comment by sglebs** [comment]
Another test case, which works with Xebium but not with your bridge:

Xebium/works:

```
!define TEST_SYSTEM {slim} 
!path ./dependencies/*

|import|
|com.xebia.incubator.xebium|

| script | selenium driver fixture |
| start browser | firefox | on url | http://www.nexxera.com/ |
| do | open | on | /pt/ |
| ensure | do | waitForElementPresent | on | id=s |
| ensure | do | type | on | id=s | with | Pagamento Eletronico |
| ensure | do | clickAndWait | on | id=searchsubmit |
| ensure | do | clickAndWait | on | link=PAGAMENTO ELETRÔNICO |
| check | is | verifyText | on | css=h2 | PAGAMENTO ELETRÔNICO |
```

Bridge/fails:

```
!define TEST_SYSTEM {slim} 
!path ./dependencies/*

|Import                            |
|nl.hsac.fitnesse.fixture.slim     |
|nl.hsac.fitnesse.fixture.slim.web |
|nl.hsac.fitnesse.fixture.slim.web.xebium |

| script | selenium driver setup |
| start driver for | firefox |

| storyboard | hsac selenium driver fixture |
| start browser | firefox | on url | http://www.nexxera.com/pt/ |
| ensure | do | waitForElementPresent | on | id=s |
| ensure | do | type | on | id=s | with | Pagamento Eletronico |
| ensure | do | clickAndWait | on | id=searchsubmit |
| ensure | do | clickAndWait | on | link=PAGAMENTO ELETRÔNICO |
| check | is | verifyText | on | css=h2 | PAGAMENTO ELETRÔNICO |
```

Error: Unable to convert target to Selenium By: link=PAGAMENTO ELETRÔNICO

**Comment by fhoeben** [comment]
Not yet. Thanks for finding it!

**Comment by fhoeben** [comment]
Can you do a pull and try the new code. By link text should now work.

**Comment by sglebs** [comment]
works like a charm :-) Thanks!

**Comment by sglebs** [comment]
Can you please update the mvn repository with this fix? I still get this problem when using this:

```
        <dependency>
                <groupId>nl.hsac</groupId>
                <artifactId>hsac-xebium-bridge</artifactId>
                <version>0.1.4</version>
        </dependency>
```

**Comment by fhoeben** [comment]
Try 0.1.5...
